<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="../Project.props" />
    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
        <Description>Cliente para acceso a la API pública de Firma Avanzada</Description>
    </PropertyGroup>

    <ItemGroup Condition="'$(UseProjectReference)' == 'true'">
        <ProjectReference Include="..\FirmarOnline.Clients.Common\FirmarOnline.Clients.Common.csproj" />
        <ProjectReference Include="..\FirmarOnline.Model.eSign\FirmarOnline.Model.eSign.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(UseProjectReference)' == 'false'">
        <PackageReference Include="FirmarOnline.Clients.Common" Version="$(ResolvedVersion)" />
        <PackageReference Include="FirmarOnline.Model.eSign" Version="$(ResolvedVersion)" />
    </ItemGroup>

</Project>
