<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net472;net8.0</TargetFrameworks>
		<IsPackable>false</IsPackable>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="xunit" Version="2.9.0" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net472'">
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.7.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FirmarOnline.Model.PSC\FirmarOnline.Model.PSC.csproj" />
	</ItemGroup>
</Project>
