<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../Version.info" />
    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
        <LangVersion>12.0</LangVersion>
    <Description>Cliente para acceso a la API pública del Prestador de Servicios de Confianza (PSC) de firmar.online</Description>
  </PropertyGroup>

    <ItemGroup Condition="'$(UseProjectReference)' == 'true'">
        <ProjectReference Include="..\FirmarOnline.Clients.Common\FirmarOnline.Clients.Common.csproj" />
        <ProjectReference Include="..\FirmarOnline.Model.PSC\FirmarOnline.Model.PSC.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(UseProjectReference)' == 'false'">
        <PackageReference Include="FirmarOnline.Clientes.Common" Version="$(ResolvedVersion)" />
        <PackageReference Include="FirmarOnline.Model.PSC" Version="$(ResolvedVersion)" />
    </ItemGroup>

</Project>