<Project>
    <PropertyGroup>
        <LangVersion>12.0</LangVersion>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <WarningLevel>7</WarningLevel>
        <Authors>edatalia data solutions, s.l.</Authors>
        <Configurations>Debug;Release;Development</Configurations>
    </PropertyGroup>
    <Import Project="Version.info" />
    <PropertyGroup Condition="$(VersionSuffix) == ''">
        <ResolvedVersion>$(VersionPrefix)</ResolvedVersion>
    </PropertyGroup>
    <PropertyGroup Condition="$(VersionSuffix) != ''">
        <ResolvedVersion>$(VersionPrefix)-$(VersionSuffix)</ResolvedVersion>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Development'">
        <UseProjectReference>true</UseProjectReference>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' != 'Development'">
        <UseProjectReference>false</UseProjectReference>
    </PropertyGroup>
</Project>